// Gateway templates — Kong, Envoy, NGINX, Traefik

type GatewayTemplateSet = {
  config: string;
  compose: string;
  env: string;
};

export const KONG_TEMPLATES: GatewayTemplateSet = {
  config: `_format_version: "3.0"

services:
{{#each services}}
  - name: {{name}}-svc
    url: http://{{upstream}}
    routes:
      - name: {{name}}-route
        paths:
          - "{{path}}"
        {{#if domain}}
        hosts:
          - {{domain}}
        {{/if}}
    plugins:
      {{#if (eq auth "jwt")}}
      - name: jwt
        config:
          secret_is_base64: false
      {{/if}}
      {{#if rateLimit}}
      - name: rate-limiting
        config:
          minute: {{rateLimit}}
          policy: local
      {{/if}}
      {{#if corsOrigins.length}}
      - name: cors
        config:
          origins:
{{#each corsOrigins}}
            - "{{this}}"
{{/each}}
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          credentials: true
      {{/if}}
{{/each}}
`,

  compose: `# Kong gateway — generated by Stackgen
services:
  kong:
    image: kong:3.7-alpine
    container_name: gateway
    restart: unless-stopped
    networks:
      - gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      {{#if (eq tls "letsencrypt")}}
      KONG_LICENSE_DATA: \$\{KONG_LICENSE_DATA\}
      KONG_SSL_CERT: /etc/kong/ssl/cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/ssl/key.pem
      {{/if}}
    ports:
      - "8000:8000"
      {{#if dashboard}}
      - "8001:8001"
      {{/if}}
      {{#if (eq tls "letsencrypt")}}
      - "8443:8443"
      {{/if}}
    volumes:
      - ./kong:/etc/kong
      {{#if (eq tls "letsencrypt")}}
      - ./ssl:/etc/kong/ssl
      {{/if}}
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  gateway:
    driver: bridge
`,

  env: `# Kong gateway environment
KONG_LICENSE_DATA=

{{#if (eq tls "letsencrypt")}}
# Let's Encrypt
LE_EMAIL={{email}}
{{/if}}
`,
};

export const ENVOY_TEMPLATES: GatewayTemplateSet = {
  config: `admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress
                route_config:
                  virtual_hosts:
{{#each services}}
                    - name: {{name}}
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "{{path}}"
                          route:
                            cluster: {{name}}-cluster
{{/each}}
                http_filters:
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router

  clusters:
{{#each services}}
    - name: {{name}}-cluster
      load_assignment:
        cluster_name: {{name}}-cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{upstream}}
                      port_value: 80
      health_checks:
        - timeout: 5s
          interval: 10s
          http_health_check:
            path: /health
{{/each}}
`,

  compose: `services:
  envoy:
    image: envoyproxy/envoy:v1.32-alpine
    container_name: gateway
    restart: unless-stopped
    networks:
      - gateway
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]

networks:
  gateway:
    driver: bridge
`,

  env: `# Envoy gateway
ENVOY_UID=0
`,
};

export const NGINX_TEMPLATES: GatewayTemplateSet = {
  config: `# NGINX reverse proxy — generated by Stackgen
{{#each services}}
server {
    listen 80;
    server_name {{#if domain}}{{domain}}{{else}}_{{name}}.local{{/if}};

    location {{path}} {
        proxy_pass http://{{upstream}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
{{/each}}
`,

  compose: `services:
  nginx:
    image: nginx:1.27-alpine
    container_name: gateway
    restart: unless-stopped
    networks:
      - gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  gateway:
    driver: bridge
`,

  env: `# NGINX gateway
`,
};

export const TRAEFIK_TEMPLATES: GatewayTemplateSet = {
  config: `# Traefik dynamic config
http:
  routers:
{{#each services}}
    {{name}}:
      rule: "PathPrefix(\`{{path}}\`)"
      service: {{name}}
{{/each}}
  services:
{{#each services}}
    {{name}}:
      loadBalancer:
        servers:
          - url: http://{{upstream}}
{{/each}}
`,

  compose: `services:
  traefik:
    image: traefik:v3.1-alpine
    container_name: gateway
    restart: unless-stopped
    networks:
      - gateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
    command:
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--accesslog=true"

networks:
  gateway:
    driver: bridge
`,

  env: `# Traefik gateway
`,
};

export const GATEWAY_README = `# Stackgen — API Gateway

Generated {{generatedAt}}. Gateway type: **{{type}}**.

## Services Routed

{{#each services}}
- **{{name}}** → \`{{upstream}}\`{{#if domain}} on domain \`{{domain}}\`{{/if}} (path: \`{{path}}\`)
{{/each}}

## Architecture

\`\`\`
Internet → :{{port}} → {{type}} Gateway → Services
                              │
                              ├─ JWT/Keycloak auth
                              ├─ Rate limit
                              └─ CORS
\`\`\`

## Files

| Path | Purpose |
|---|---|
| \`{{ type }}.yml\` (or \`.conf\`/\`.yaml\`) | Gateway config |
| \`docker-compose.yml\` | Run gateway |
| \`.env.example\` | Secrets |

## Step-by-Step

### 1. Place gateway next to your services

\`\`\`bash
# Copy gateway bundle to a directory reachable from your services
cp -r gateway/* /opt/gateway/
\`\`\`

### 2. Join gateway network with services

Update your services compose to use the \`gateway\` network:

\`\`\`yaml
networks:
  default:
  gateway:
    external: true
\`\`\`

\`\`\`bash
docker network create gateway
docker compose -f your-services.yml up -d
docker compose -f gateway/docker-compose.yml up -d
\`\`\`

### 3. Verify routing

\`\`\`bash
curl http://localhost/{{services.0.path}}
{{#if dashboard}}
# Kong dashboard: http://localhost:8001
{{/if}}
{{#if (eq tls "letsencrypt")}}
# TLS: https://localhost:8443
{{/if}}
\`\`\`

### 4. Enable TLS (if Let's Encrypt)

\`\`\`bash
# Add to your DNS: point domain to gateway host
# Certbot or Caddy can auto-renew

# Or use Caddy in front of gateway:
# docker compose -f caddy/docker-compose.yml up -d
\`\`\`

---

Generated by [Stackgen](https://stackgen.denisetiya.site)
`;
